lab2/Models/ErrorViewModel.cs
using System;

namespace lab2.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

lab2/Models/MyModel.cs
using Microsoft.AspNetCore.Mvc.ActionConstraints;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace lab2.Models
{
    public class MyModel
    {
        public int num1 { get; set; }
        public int num2 { get; set; }
        public string act { get; set; }
       
    }
}

lab2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using lab2.Models;

namespace lab2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

lab2/Controllers/MyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using lab2.Models;

namespace lab2.Controllers
{
    public class MyController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        private MyModel myModel = new MyModel();
        public Tuple<string, string> Actions(int? num1, string act, int? num2)
        {
            string answ = "";
            int? res = 0;
            var map = new Tuple<string, string>("", "");
            switch (act)
            {
                case "add":
                    res = num1 + num2;
                    answ = res.ToString();
                    act = "+";
                    break;
                case "sub":
                    res = num1 - num2;
                    answ = res.ToString();
                    act = "-";
                    break;
                case "mult":
                    res = num1 * num2;
                    answ = res.ToString();
                    act = "*";
                    break;
                case "div":
                    if (num2 == 0)
                    {
                        answ = "Divide by zero!";
                        act = "/";
                        break;
                    }
                    else
                    {
                        res = num1 / num2;
                        answ = res.ToString();
                        act = "/";
                        break;
                    }
            }
            map = Tuple.Create(act, answ);
            return map;
        }
        public IActionResult ManualView(int? num1, string act, int? num2)
        {
            if (Request.Method == "GET")
                return View("ManualView");
            if (Request.Method == "POST")
            {
                Tuple<string, string> resmap = Actions(num1, act, num2);

                string data = $"{num1} {resmap.Item1} {num2} = {resmap.Item2}";
                ViewData["Result"] = data;

                return View("ResultView");
            }
            return View("Index");
        }
        [HttpGet]
        public IActionResult ManualWithSeparateHandlersView()
        {
            return View("ManualWithSeparateHandlersView");
        }
        [HttpPost]
        public IActionResult ManualWithSeparateHandlersView(int num1, string act, int num2)
        {
            Tuple<string, string> resmap = Actions(num1, act, num2);

            string data = $"{num1} {resmap.Item1} {num2} = {resmap.Item2}";
            ViewData["Result"] = data;

            return View("ResultView");
        }
        [HttpGet]
        public IActionResult ModelBindingParamView()
        {
            return View("ModelBindingParamView");
        }
        [HttpPost]
        public IActionResult ModelBindingParamView(int mnum1, string mact, int mnum2)
        {
            Tuple<string, string> resmap = this.Actions(mnum1, mact, mnum2);

            string data = $"{mnum1} {resmap.Item1} {mnum2} = {resmap.Item2}";
            ViewData["Result"] = data;

            return View("ResultView");
        }
        [HttpGet]
        public IActionResult ModelBindingSeparateView()
        {
            return View("ModelBindingSeparateView");
        }
        [HttpPost]
        public IActionResult ModelBindingSeparateView(MyModel model)
        {
            Tuple<string, string> resmap = this.Actions(model.num1, model.act, model.num2);

            string data = $"{model.num1} {resmap.Item1} {model.num2} = {resmap.Item2}";
            ViewData["Result"] = data;

            return View("ResultView");
        }
    }
}

lab2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div>
    <h1 class="display-4">Form parameters parsing demo</h1>
    <ul>
        <li>
            <a asp-controller="My" asp-action="ManualView"> Manual parsing in single action </a>
        </li>
        <li>
            <a asp-controller="My" asp-action="ManualWithSeparateHandlersView"> Manual parsing in separate actions </a>
        </li>
        <li>
            <a asp-controller="My" asp-action="ModelBindingParamView"> Model binding (parameters) </a>
        </li>
        <li>
            <a  asp-controller="My" asp-action="ModelBindingSeparateView"> Model binding (separate model) </a>
        </li>
    </ul>
</div>

lab2/Views/Shared/ManualView.cshtml
@model lab2.Models.MyModel

@{
    ViewData["Title"] = "ManualView";
}
<div>
    <h1 class="display-4">Manual</h1>
    <form method="post">
        <input name="num1" />
        <br />
        <select name="act">
            <option value="add">+</option>
            <option value="sub">-</option>
            <option value="mult">*</option>
            <option value="div">/</option>
        </select>
        <br />
        <input name="num2" />
        <br />
        <input type="submit" value="Submit" />
        <br />
    </form>
</div>

lab2/Views/Shared/ManualWithSeparateHandlersView.cshtml
@model lab2.Models.MyModel

@{
    ViewData["Title"] = "ManualWithSeparateHandlersView";
}
<div>
    <h1 class="display-4">Manual</h1>
    <form method="post">
        <input name="num1" />
        <br />
        <select name="act">
            <option value="add">+</option>
            <option value="sub">-</option>
            <option value="mult">*</option>
            <option value="div">/</option>
        </select>
        <br />
        <input name="num2" />
        <br />
        <input type="submit" value="Submit" />
        <br />
    </form>
</div>

lab2/Views/Shared/ModelBindingParamView.cshtml
@model lab2.Models.MyModel

@{
    ViewData["Title"] = "ModelBindingParamView";
}
<div>
    <h1 class="display-4">Manual</h1>
    <form method="post">
        <input name="mnum1" />
        <br />
        <select name="mact">
            <option value="add">+</option>
            <option value="sub">-</option>
            <option value="mult">*</option>
            <option value="div">/</option>
        </select>
        <br />
        <input name="mnum2" />
        <br />
        <input type="submit" value="Submit" />
        <br />
    </form>
</div>

lab2/Views/Shared/ModelBindingSeparateView.cshtml
@model lab2.Models.MyModel

@{
    ViewData["Title"] = "ModelBindingSeparateView";
}
<div>
    <h1 class="display-4">Manual</h1>
    <form method="post">
        <input name="num1" />
        <br />
        <select name="act">
            <option value="add">+</option>
            <option value="sub">-</option>
            <option value="mult">*</option>
            <option value="div">/</option>
        </select>
        <br />
        <input name="num2" />
        <br />
        <input type="submit" value="Submit" />
        <br />
    </form>
</div>

lab2/Views/Shared/ResultView.cshtml
@{
    ViewData["Title"] = "Result";
}

<h1>Result</h1>
<br>
<h4>@ViewData["result"]</h4>

lab2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Backend2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">lab2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>     
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Backend2 <a asp-area="" asp-controller="Home"></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>